import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/context/providers";

// 配置 Jost 字体
const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost", // 定义 CSS 变量名
  display: "swap",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={jost.variable}>
      <body className="font-sans antialiased">
        <Providers>{children}</Providers> {/*  只在 body 里使用 Client Component */}
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};